name: main branch action

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # - name: Build
      #   run: npm run build

      - name: Deploy to server
        run: |
          touch id_rsa
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          scp -i id_rsa -o StrictHostKeyChecking=no -r ./* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/action-playground

      - name: Execute remote script
        run: |
          ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          cd /home/ubuntu/action-playground;
          ls > dirls;
          "
          
          
